#!/bin/sh
#       ____  __  ______________
#      / __ \/ / / /  _/ ___/__ \
#     / / / / /_/ // / \__ \__/ /
#    / /_/ / __  // / ___/ / __/
#   /_____/_/ /_/___//____/____/
#
#   DHIS2 restore database backup

set -e

PROG=$(basename "$0")
BACKUPFILE="$1"
DB="$2"
PG=${3:-postgres}

usage() {
  echo "Usage: $PROG <backup file (tar.gz)> <dbname> <pgcontainer>"
  echo "  backup file: database dump in tar gzip format"
  echo "  dbname: the name of the database to restore"
  echo "  pgcontainer: the name of the postgres container holding the dbname"
  echo "Options:"
  echo "  -h, --help       Display this help message"
}

[ -z "${BACKUPFILE}"  ] || [ -z "${DB}" ] && usage && exit 1

if [ ! $(lxc list -c n --format csv | grep -x $DB) ]; then
  echo "Error: No such container named '$DB'"
  exit 1
fi

if [ ! $(lxc list -c n --format csv | grep -x $PG) ]; then
  echo "Error: No such container named '$PG'"
  exit 1
fi

if [ `lxc exec "$DB" -- systemctl is-active tomcat9` = "active" ]; then
  echo "Cannot restore database while tomcat is running."
  echo "First stop it by running lxc exec $DB -- service tomcat9 stop"
  exit 1
fi

echo "Dropping database $DB..."
sudo lxc exec $PG dropdb "$DB"

echo "Recreating database..."
sudo lxc exec $PG -- createdb -O "$DB" "$DB"

echo "Restoring data to database..."
zcat "${BACKUPFILE}" | grep -v 'ALTER .* OWNER' | sudo lxc exec $PG -- psql "$DB"
echo "REASSIGN OWNED BY root TO $DB" | sudo lxc exec $PG -- psql "$DB"

if [ "$?" -eq 0 ]; then
  echo "Done!"
  echo "You can now restart tomcat by running lxc exec $DB -- service tomcat9 start"
fi
