#!/usr/bin/env bash
#       ____  __  ______________
#      / __ \/ / / /  _/ ___/__ \
#     / / / / /_/ // / \__ \__/ /
#    / /_/ / __  // / ___/ / __/
#   /_____/_/ /_/___//____/____/
#
#   Script to completely remove a dhis2 instance

source libs.sh
source parse_config.sh

PROG=`basename $0`

###############################################################
usage() {
  echo "Usage: $PROG <name> [<postgres_container>]"
  echo "  name: name of the dhis2 container"
  echo "  postgres_container: name of the postgres container"
  echo "Options:"
  echo "  -h, --help       Display this help message"
}

while getopts h opt
do
  case $opt in
    h) usage; exit 1;;
    *) log_error "Error: Unknown parameter '$OPTARG'."
        exit 1;;
  esac
done
shift $(($OPTIND - 1))

if [ "$#" -lt 2 ]; then
  usage
  exit 1
fi

NAME=$1
DBCONTAINER=${2:-postgres}

log_info "Removing proxy configuration"
if [[ $PROXY == "nginx" ]]; then
  lxc exec proxy -- rm /etc/nginx/upstream/${NAME}.conf
  if [[ $APM == "glowroot" ]]; then
    lxc exec proxy -- rm /etc/nginx/upstream/${NAME}-glowroot.conf
  fi
  lxc exec proxy -- service nginx restart
elif [[ $PROXY == "apache2" ]]; then
  lxc exec proxy -- rm /etc/apache2/upstream/${NAME}
  if [[ $APM == "glowroot" ]]; then
    lxc exec proxy -- rm /etc/apache2/upstream/${NAME}-glowroot
  fi
  lxc exec proxy -- service apache2 restart
else
  log_error "Error: Proxy type not supported"
  exit 1
fi

log_info "Deleting container"
container_exist=$(lxc list -c n | grep -w $NAME)
if ! [ -z "$container_exist" ]; then
  log_warn "Container '$NAME' does not exit"
else
  lxc stop $NAME
  lxc delete $NAME
fi

log_info "Removing database user and db"
lxc exec ${DBCONTAINER} -- dropdb $NAME
lxc exec ${DBCONTAINER} -- dropuser $NAME

# Remove glowroot credentials
log_info "Removing glowroot credentials"
remove_creds "${NAME}-glowroot"

sudo sed -i "/.* $N$/d" /etc/hosts
